name: 'Extract target'
description: Extracts target to bump in version

inputs:
  major:
    description: 'Trigger for major version'
    required: true
    type: boolean

  minor:
    description: 'Trigger for minor version'
    required: true
    type: boolean

  patch:
    description: 'Trigger for patch version'
    required: true
    type: boolean

outputs:
  target: 
    description: A semver target to bump
    value: ${{ steps.extract.outputs.target }}

runs:
  using: "composite"

  steps:
    - name: ðŸ” Extract target
      id: extract
      shell: bash
      run: |
        target="";
        if [[ $MAJOR == "true" ]]; then
          target="major"
        elif [[ $MINOR == "true" ]]; then
          target="minor"
        elif [[ $PATCH == "true" ]]; then
          target="patch"
        fi;
        echo "target=${target}" >> "$GITHUB_OUTPUT"
      env:
        MAJOR: '${{ inputs.major }}'
        MINOR: '${{ inputs.minor }}'
        PATCH: '${{ inputs.patch }}'
        