name: 'Extract target'
description: Extracts target to bump in version

inputs:
  major:
    description: 'Trigger for major version'
    required: true

  minor:
    description: 'Trigger for minor version'
    required: true

  patch:
    description: 'Trigger for patch version'
    required: true

  bump_build:
    description: Whether to bump the build number
    required: true

outputs:
  target: 
    description: A semver target to bump
    value: ${{ steps.extract.outputs.target }}

runs:
  using: "composite"

  steps:
    - name: ðŸ” Extract target
      id: extract
      shell: bash
      run: |
        target="";
        if [[ $MAJOR == "true" ]]; then
          target="major,"
        fi;
        
        if [[ $MINOR == "true" ]]; then
          target="${target}minor,"
        fi;

        if [[ $PATCH == "true" ]]; then
          target="${target}patch,"
        fi;

        if [[ $BUILD == "true" ]]; then
          target="${target}build-number,"
        fi;

        target="$(echo "${target}" | sed 's/.$//')"

        echo "target=$target" >> "$GITHUB_OUTPUT"
      env:
        MAJOR: '${{ inputs.major }}'
        MINOR: '${{ inputs.minor }}'
        PATCH: '${{ inputs.patch }}'
        BUILD: '${{ inputs.bump_build }}'
        