name: 'Bump version'
description: Bumps semVer version string

inputs:
  targets:
    description: 'A SEMVER version target - major/minor/patch/build-number'
    default: "null"
    required: true

  strategy:
    description: 'Whether to use relative/absolute versioning'
    default: "relative"
    required: false

  path:
    description: 'Path to find the yaml/json file'
    default: 'pubspec.yaml'
    required: false

  use-pub:
    description: 'Whether to use dart to activate package'
    default: "true"
    required: false

  pub-version:
    description: 'Package version to use from pub'
    default: "1.0.0"
    required: false

  source-path:
    description: 'Path to local package path'
    default: '.'
    required: false

runs:
  using: "composite"

  steps:
    # Make sure you activate dart sdk!
    - name: ⚡ Activate Magical Bump CLI
      shell: bash
      run: |
        if [[ "${{inputs.use-pub}}" == "true" ]]; then
          dart pub global activate magical_version_bump ${{inputs.pub-version}}
        else
          dart pub global activate --source=path "${{inputs.source-path}}"
        fi

    - name: ✅ Bump version
      shell: bash
      run: mag modify bump --targets "${{inputs.targets}}" --strategy "${{inputs.strategy}}" --dir "${{inputs.path}}"